### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by markusd1984** [longxinH/xhprof#10]
after cloning git and entering the extension folder of xhprof, what then?

I don't understand the 3rd line "/path/to/php7/bin/phpize" 

```
git clone https://github.com/longxinH/xhprof.git ./xhprof
cd xhprof/extension/
/path/to/php7/bin/phpize
./configure --with-php-config=/path/to/php7/bin/php-config
make && sudo make install
```

**Comment by longxinH** [comment]
/path/to/php7/ means your php installation directory

**Comment by markusd1984** [comment]
thanks, didn't realise it should execute phpsize , working now.
