### ISSUE TITLE
3 tests failed

### ISSUE THREAD

**Issue by markusd1984** [longxinH/xhprof#11]
The below **3 tests failed** even though php.info is showing xhprof v 2.0.1 is enabled. 

I also have "php_admin_value auto_prepend_file /var/www/html/xhgui/external/header.php" in my apache vhost but unfortunately no profiling is happening. Pleas help.

```
FAILED TEST SUMMARY
---------------------------------------------------------------------
XHProf: Basic Profiling Test
Author: Kannan [tests/xhprof_001.phpt]
XHProf: Test Include File (load/run_init operations)
Author: Kannan [tests/xhprof_004.phpt]
XHProf: Test excluding call_user_func and similar functions
Author: mpal [tests/xhprof_007.phpt]
=========================================
```

**Comment by longxinH** [comment]
xhgui please check related documents

**Comment by markusd1984** [comment]
@longxinH but isn't this an **xhprof installation** issue following make test?!?

**Comment by longxinH** [comment]
```
<?php
xhprof_enable(XHPROF_FLAGS_CPU | XHPROF_FLAGS_MEMORY);
function demo() {
    return md5(123);
}
demo();
var_dump(xhprof_disable());
```
@markusd1984 Can you try to print out the data if you have proof that the extension is available?

**Comment by markusd1984** [comment]
```
/var/www/html/opigno/xhprof.php:18:
array (size=10)
  'main()==>curl_init' => 
    array (size=5)
      'ct' => int 1
      'wt' => int 5930
      'cpu' => int 4916
      'mu' => int 1832
      'pmu' => int 0
  'main()==>curl_setopt' => 
    array (size=5)
      'ct' => int 3
      'wt' => int 8
      'cpu' => int 11
      'mu' => int 760
      'pmu' => int 0
  'main()==>curl_getinfo' => 
    array (size=5)
      'ct' => int 1
      'wt' => int 7
      'cpu' => int 7
      'mu' => int 3208
      'pmu' => int 0
  'main()==>curl_exec#http://www.baidu.com' => 
    array (size=5)
      'ct' => int 1
      'wt' => int 1993048
      'cpu' => int 2693
      'mu' => int 17000
      'pmu' => int 0
  'main()==>curl_close' => 
    array (size=5)
      'ct' => int 1
      'wt' => int 2
      'cpu' => int 3
      'mu' => int 600
      'pmu' => int 0
  'main()==>A::__construct' => 
    array (size=5)
      'ct' => int 5
      'wt' => int 3
      'cpu' => int 6
      'mu' => int 920
      'pmu' => int 0
  'main()==>A::__destruct' => 
    array (size=5)
      'ct' => int 5
      'wt' => int 3
      'cpu' => int 5
      'mu' => int 920
      'pmu' => int 0
  'main()==>md5' => 
    array (size=5)
      'ct' => int 1
      'wt' => int 11
      'cpu' => int 11
      'mu' => int 688
      'pmu' => int 0
  'main()==>xhprof_disable' => 
    array (size=5)
      'ct' => int 1
      'wt' => int 0
      'cpu' => int 1
      'mu' => int 920
      'pmu' => int 0
  'main()' => 
    array (size=5)
      'ct' => int 1
      'wt' => int 1999154
      'cpu' => int 7767
      'mu' => int 23864
      'pmu' => int 0
```

**Comment by longxinH** [comment]
Prove that the extension is already available

**Comment by markusd1984** [comment]
php.info: 
xhprof support | enabled
-- | --
Version | 2.0.1

![image](https://user-images.githubusercontent.com/24621214/43067059-2e22fdd0-8e5e-11e8-939e-45126bf69091.png)

**Comment by andypost** [comment]
Trying to build package for AlpineLinux and faced with the same 3 failed tests https://github.com/alpinelinux/aports/pull/4923 (I did disabled them for now)

But looks that caused by `XHPROF_FLAGS_NO_BUILTINS` is set by default somehow, it causing `strlen` is not displayed
```
xhprof-2.0.1/extension/tests$ cat xhprof_001.diff 
003- foo==>strlen                            : ct=       1; wt=*;
010- foo==>strlen                            : cpu=*; ct=       1; wt=*;
022- foo==>strlen                            : ct=       1; mu=*; pmu=*; wt=*;
029- foo==>strlen                            : cpu=*; ct=       1; mu=*; pmu=*; wt=*;
```

**Comment by longxinH** [comment]
Thanks, I am going to locate the problem and fix it now.

**Comment by longxinH** [comment]
@markusd1984 @andypost The latest master branch has fixed tests failed, please verify

**Comment by andypost** [comment]
Thanx it pass tests now! checking how that now works)

**Comment by andypost** [comment]
@longxinH not clear why `strlen` still not displayed in results, I'm using `php examples/sample.php` to check other functions.
Looks like language elements like `echo`, `print` also is not caught. Maybe there's reason for that

**Comment by longxinH** [comment]
@andypost This is an optimization of php7, strlen these functions do not execute the underlying zend_execute_ex, so can not capture the analysis, my guess is that such functions will not cause performance problems, and strlen belongs to c function, php chooses to call directly

**Comment by andypost** [comment]
@longxinH Thank for explanation, are planning to make new release?

**Comment by longxinH** [comment]
@andypost new release https://github.com/longxinH/xhprof/releases/tag/v2.0.2

**Comment by andypost** [comment]
@longxinH thanks, packages released https://pkgs.alpinelinux.org/packages?name=php7-xhprof*&branch=edge

**Comment by longxinH** [comment]
@andypost This is very good
