### ISSUE TITLE
Warning: PHP Startup: xhprof: Unable to initialize module

### ISSUE THREAD

**Issue by xcpschen** [longxinH/xhprof#18]
mac ,php7.2.11 安装这个拓展后，出现这个提示。
Warning: PHP Startup: xhprof: Unable to initialize module
Module compiled with module API=20160303
PHP    compiled with module API=20170718
按你们给你的安装条件，我的php 应该是满足条件的，怎么回出现这个版本不匹配的提示。

**Comment by longxinH** [comment]
检查phpize 是否跟php版本一致

**Comment by xcpschen** [comment]
phpize -v
Configuring for:
PHP Api Version:         20170718
Zend Module Api No:      20170718
Zend Extension Api No:   320170718

**Comment by longxinH** [comment]
你详细的安装步骤是怎样的？

**Comment by xcpschen** [comment]
我找到原因了，我机器上有两个版本的php,由于配置问题，导致浏览器访问时转到另一个版本去。
