### ISSUE TITLE
Mac下，统计的时间单位有问题

### ISSUE THREAD

**Issue by shaoshiqiang** [longxinH/xhprof#26]
![image](https://user-images.githubusercontent.com/41774538/60172770-f3134a00-983f-11e9-9e5c-6a098b95ce48.png)

![image](https://user-images.githubusercontent.com/41774538/60172699-c19a7e80-983f-11e9-8a29-90d465badfc6.png)

只是加载了扩展而已，显示的是500多ms，是不是在Mac下时间单位有问题？

**Comment by longxinH** [comment]
在linux下是一样的吗

**Comment by reatang** [comment]
我也出现了这个问题 [我的提问](https://github.com/longxinH/xhprof/issues/31)

**Comment by longxinH** [comment]
最新分支已修复mac下时间基准问题
