### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by madjoe** [longxinH/xhprof#27]
Is there a script/instruction on how to uninstall this script? Thanks.

**Comment by longxinH** [comment]
Uninstalling only needs to comment out ```xhprof.so``` and the code removes ```xhprof_enable``` and ```xhprof_disable```

**Comment by madjoe** [comment]
Thank you. I should probably also delete `/usr/lib/php/modules/xhprof.so`. Is there any other such leftover, no?

**Comment by longxinH** [comment]
So file can not be deleted, as long as the comment php.ini xhprof.so loaded

**Comment by madjoe** [comment]
I just wondered if there is any other file I should delete?

**Comment by longxinH** [comment]
No need！

**Comment by madjoe** [comment]
Ok, thanks.
