### ISSUE TITLE
Please add dll for Windows

### ISSUE THREAD

**Issue by lilumi** [longxinH/xhprof#34]
Please add dll for Windows into releases on github or here: https://windows.php.net/downloads/pecl/releases/xhprof/

**Comment by cmb69** [comment]
The extension is currently not compatible with Windows; PR #35 solves some basic issues.

**Comment by cmb69** [comment]
BTW, the binary packages at https://windows.php.net/downloads/pecl/releases/xhprof/ are built automatically whenever a new version of xhprof is released.

**Comment by longxinH** [comment]
@cmb69 Do I need to download Visual C ++ to compile the dll?

**Comment by cmb69** [comment]
If you want to compile the DLL yourself, you have to install Visual Studio and follow the [build instructions](https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2).

**Comment by longxinH** [comment]
@cmb69 I have released version 2.1.4, but it does not compile windows automatically https://windows.php.net/downloads/pecl/releases/xhprof/

**Comment by longxinH** [comment]
@cmb69 I released a 2.1.4-bata version, but the dll is not generated https://pecl.php.net/package/xhprof/2.1.4

**Comment by cmb69** [comment]
The build tools would need something like https://github.com/php/web-rmtools/pull/13 to be able to build xhprof.

**Comment by Jan-E** [comment]
@lilumi The php_xhprof.dll's can also be found in all my PHP 7.0 - 7.4 builds on https://www.apachelounge.com/viewtopic.php?t=6359 (even for PHP 7.0 & 7.1).

**Comment by Jan-E** [comment]
And @cmb69 made them available on windows.php.net as well: https://github.com/php/web-rmtools/pull/13#issuecomment-567029321

**Comment by longxinH** [comment]
@lilumi Refer to @laruence .appveyor.yml configuration, successfully compile window dll [https://ci.appveyor.com/project/longxinH/xhprof](url)

**Comment by cmb69** [comment]
DLLs are also [available on PECL](https://pecl.php.net/package/xhprof/2.2.0/windows) now.
