### ISSUE TITLE
how turn on extra collection with Mysql? 

### ISSUE THREAD

**Issue by dennsliu** [longxinH/xhprof#39]
how turn on extra collection with Mysql?

**Comment by longxinH** [comment]
php.ini adds xhprof.collect_additional_info = 1

**Comment by dennsliu** [comment]
ok, thanks, I add blew configure for xhprof.

[xhprof]
extension = xhprof.so
xhprof.output_dir = "/var/www/xhprof/output_dir"
xhprof.collect_additional_info = 1

how to config mysql host, user name and password, let Xhprof can connect mysql ?

**Comment by longxinH** [comment]
xhprof does not help you connect mysql
