### ISSUE TITLE
Won't compile against PHP 7.2

### ISSUE THREAD

**Issue by langemeijer** [longxinH/xhprof#4]
Compiling to 7.2 I get:
```
/root/pecl-packages/xhprof/build-7.2/xhprof.c:890:44: error: too many arguments to function 'php_pcre_replace_impl'
                         zend_string *res = php_pcre_replace_impl(pce_regexp, NULL, Z_STRVAL(tmp_zv), Z_STRLEN(tmp_zv), &repl, 0, 1, 0);
                                            ^
```

This is a change in php_pcre_replace_impl, as documented here: https://raw.githubusercontent.com/php/php-src/PHP-7.2.0/UPGRADING.INTERNALS under '3. Module changes':

>   . php_pcre_replace and php_pcre_replace_impl expect a zend_string instead of a zval and
>     is_callable_replace options is removed:
>     - PHPAPI zend_string *php_pcre_replace(zend_string *regex, zend_string *subject_str, char *subject, int subject_len, zend_string *replace_str, int limit, int *replace_count);
>     - PHPAPI zend_string *php_pcre_replace_impl(pcre_cache_entry *pce, zend_string *subject_str, char *subject, int subject_len, zend_string *replace_str, int limit, int *replace_count);

**Comment by longxinH** [comment]
fixed
