### ISSUE TITLE
Package installed, but PHP not loading extension

### ISSUE THREAD

**Issue by paul-gene** [longxinH/xhprof#41]
I followed the instructions to clone the repo and "make" the extension.

I added the config lines to php.ini, and restarted php 7.2 fpm and nginx. but when I dump phpinfo(), the extension simply isn't loading.

**Comment by longxinH** [comment]
Please check your installation steps again
```
git clone https://github.com/longxinH/xhprof.git ./xhprof
cd xhprof/extension/
/path/to/php7/bin/phpize
./configure --with-php-config=/path/to/php7/bin/php-config
make
make install
```
php.ini
```
extension = xhprof.so
```
Check installation
```
/path/to/php7/bin/php --ri xhprof
```

**Comment by paul-gene** [comment]
I have multiple PHP versions installed, and I had ran `phpize` as the wrong version. Finally got it installed!
