### ISSUE TITLE
Segmentation fault with PHP = 8.0 while adding call_user_func_xxxx to the to ignored_functions option

### ISSUE THREAD

**Issue by stronk7** [longxinH/xhprof#72]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

This is how we enable xhprof since the night of times ([link](https://github.com/moodle/moodle/blob/master/lib/xhprof/xhprof_moodle.php#L169-L177)):
```
$ignore = array('call_user_func', 'call_user_func_array');
xhprof_enable(XHPROF_FLAGS_CPU + XHPROF_FLAGS_MEMORY, array('ignored_functions' => $ignore));
```
Notes: 
- By replacing the ignored by anything else (say `echo` or `print_r`... ) or not passing the option at all, the profiling goes ok.
- PHP 7.4 and older don't seem to be affected, only PHP 8.0 and up.

2. What did you expect to see?

Profiling to work properly for web requests.

4. What did you see instead

Consistent segmentation faults with Apache.
Note: Haven't been able to reproduce them with our CLI scripts neither with [/examples/sample.php](https://github.com/longxinH/xhprof/blob/master/examples/sample.php) modified to enable profiling our way.

5. What is your Xhprof version?

Reproduced with 2.3.5, 2.3.7 and current master's HEAD.

**Comment by stronk7** [comment]
Extra info: Just to discard if the problem may be some other extension playing badly with xhprof (I've a legion), I've tried progressively disabling all them. With no extensions installed (but xhprof itself, heh), I still got the consistent seg faults.

**Comment by stronk7** [comment]
Little update: I'm trying to debug what's going here and at which point it's failing... I've been able to reproduce the problem also in a couple of CLI scripts we have, that makes things easier to try.

My current hunch is that it's related to shutdown registered functions and something being executed within them, because I've traced some of the crashes to an `exit(0)` call in the CLI script... but I still have to trace it down a little bit more.

Just sharing the potential relation with shutdown registered functions in case it hits somebody else brilliant idea.

Ciao :-)

**Comment by longxinH** [comment]
@stronk7 The following example is under PHP8.0.22, and no segmentation fault occurs. Can you provide a reproduced example?
```php
function increment($var)
{
    $var++;
}

$ignore = array('call_user_func', 'call_user_func_array');
xhprof_enable(XHPROF_FLAGS_CPU + XHPROF_FLAGS_MEMORY, array('ignored_functions' => $ignore));

$a = 0;
call_user_func('increment', $a);

$output = xhprof_disable();
```

**Comment by stronk7** [comment]
I'm really having problems trying to reproduce this out from [Moodle](https://github.com/moodle/moodle), though can reproduce it consistently within it (and only if those 2 functions are added to the ignore list).

Still trying hard to be able to simulate it... in an isolated script... will share any findings...

**Comment by longxinH** [comment]
@stronk7 try the latest master branch.

**Comment by stronk7** [comment]
Yay, I've just tested the master build with PHP 7.4, 8.0 and 8.1 and can confirm that it's back to work.

No more crashes and the profiling runs are being stored and later reported (callgraphs included), perfectly!

Great achievement, thanks!

**Comment by longxinH** [comment]
https://github.com/longxinH/xhprof/releases/tag/v2.3.8
